# Use the latest Golang image
FROM golang:1.22.3-alpine3.19

# Install necessary tools
RUN apk add --no-cache git curl bash

# Install air for live reloading using the provided install.sh script
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

# Set the working directory inside the container
WORKDIR /app

# Copy the Go module definition files to the working directory
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy all source files to the working directory
COPY . .

# Expose port 8080
EXPOSE 8080

# Command to run air for live reloading
CMD ["air"]
