name: Deploy Go Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Install dependencies
      run: |
        cd backend
        go mod download
        
    - name: Build
      run: |
        cd backend
        go build -o app
        
    - name: Deploy
      run: |
        # Create deployment directory
        mkdir -p $HOME/colosseum-backend
        cp backend/app $HOME/colosseum-backend/
        
        # Kill existing process if running
        pkill -f colosseum-backend || true
        
        # Start the new process in background
        nohup $HOME/colosseum-backend/app > $HOME/colosseum-backend/app.log 2>&1 &
        
        # Save PID for future reference
        echo $! > $HOME/colosseum-backend/app.pid