name: Deploy Go Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        
    - name: Install dependencies
      run: |
        cd backend
        go mod download
        
    - name: Build
      run: |
        cd backend
        go build -o app
        
    - name: Deploy
      run: |
        # Create a deployment directory with correct permissions
        mkdir -p $HOME/colosseum-backend
        cp backend/app $HOME/colosseum-backend/
        
        # Use systemctl with --user flag for user-level service
        systemctl --user stop colosseum-backend || true
        systemctl --user start colosseum-backend